### ISSUE TITLE
Always focus tab left of the closed tab

### ISSUE THREAD

**Issue by SanderBouwhuis** [giantoppai/TST-Focus-Preceding-Tab-On-Close#10]
Is it possible to have an option / build where you ALWAYS go to the previous tab, regardless whether it's a child or sibling tab?
I always want to select the tab left of the closed tab. Now, it selects the tab on the left as long as it's not the first child in a group. But, if it is the first child in a group it will go to the tab right of the closed tab.
This inconsistency makes it really confusing to use this.

I currently use the 'Activate left tab on close' extension for this, but it doesn't work as nicely. After closing a tab it first goes to the tab to the right of the closed tab, and then visibly jumps to the tab left of that tab.

**Comment by SanderBouwhuis** [comment]
Nevermind. I fixed it by downloading an addon called 'ActivateLeftTabOnClose'.
Interestingly, that addon had the exact same problem as your addon. After asking the developer whether (s)he could fix this, (s)he actually managed to do it within a few hours!
If you check how (s)he fixed it, you probably can use the same strategy. Good luck!

**Comment by giantoppai** [comment]
Thanks for bringing this to my attention. It's a very good addon.
