### ISSUE TITLE
Extension doesn't work

### ISSUE THREAD

**Issue by giantoppai** [giantoppai/TST-Focus-Preceding-Tab-On-Close#5]
Pardon me, @Lej77, do you have spare time to check out the problem?
TST developer said that most tab properties that needed permissions should now be exposed with the update so there's no need for reforms. However, the extension seems to not work anymore due to an unknown reason.

Instead of focusing the preceding tab with the extension, TST will still focus the next tab after closing the current tab.
In debug console, it says "Error: Invalid tab ID [number]" when the second to last child tab is closed.
This is tested using latest Firefox 67.0.1.

**Comment by Lej77** [comment]
@giantoppai I have created a pull request #6 that should make the extension work again.
