### ISSUE TITLE
timeSinceTabBecameActive

### ISSUE THREAD

**Issue by giantoppai** [giantoppai/TST-Focus-Preceding-Tab-On-Close#8]
@Lej77 There seems to be a bug where closing a lot of tabs based on a certain timing will focus the next tab instead of the preceding tab.

Changing line 234
from
`if (timeSinceTabBecameActive > 250) {` 
to
`if (timeSinceTabBecameActive > 500) {` 
seems to fix it.

Will doing so cause any issues?

**Comment by Lej77** [comment]
It shouldn't. That setting affects how long the time between the tabClosed event and the tab becoming inactive can be. If a tab becomes in-active and 500ms pass and then the tabClosed event triggers then that tab will be considered closed while active and the focus override code will be used. 

So this change could cause issues if the user quickly switches tab and then closes the tab they switched from. But 500ms is quite fast so I don't think it will actually be a problem.

**Comment by giantoppai** [comment]
Thank you for the explanation. I'm not exactly sure why this change fixes it but if there's no issue, I will update it.
