### ISSUE TITLE
Extension causes last tab in tree to lose focus in favor of previous

### ISSUE THREAD

**Issue by I60R** [giantoppai/TST-Focus-Preceding-Tab-On-Close#9]
E.g. when I open a new tab page it instantly loses focus and I must click Ctrl+Tab to restore focus. 

Firefox version: 67
TST version: 3.1.5

**Comment by giantoppai** [comment]
@I60R sorry for the late reply. Can you provide detailed steps to replicate your issue?

**Comment by I60R** [comment]
Yes

1) Install the addon
2) Ctrl+T
3) type something in the address bar
4) Enter

At this point focus moves to the previous tab.

Looks like Firefox treats a new tab page as closed when I press the Enter.

It also not depends on custom tab page addons / new tab page settings in Firefox preferences.

**Comment by giantoppai** [comment]
Sorry, I can't seem to replicate your issue. 
I recommend using "Activate Left Tab On Close" as suggested by another user.
https://addons.mozilla.org/en-US/firefox/addon/activate-left-tab-on-close/
